import { useState, useEffect, useRef, useCallback } from 'react';

/* ────────────────────────────────────────────────────────────
 *  SVG Icons — professional, consistent stroke-based icons
 * ──────────────────────────────────────────────────────────── */
const Icons = {
  book: (
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20" /><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z" />
    </svg>
  ),
  refresh: (
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <polyline points="23 4 23 10 17 10" /><polyline points="1 20 1 14 7 14" /><path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15" />
    </svg>
  ),
  zap: (
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" />
    </svg>
  ),
  users: (
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2" /><circle cx="9" cy="7" r="4" /><path d="M23 21v-2a4 4 0 0 0-3-3.87" /><path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  ),
  wifiOff: (
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <line x1="1" y1="1" x2="23" y2="23" /><path d="M16.72 11.06A10.94 10.94 0 0 1 19 12.55" /><path d="M5 12.55a10.94 10.94 0 0 1 5.17-2.39" /><path d="M10.71 5.05A16 16 0 0 1 22.56 9" /><path d="M1.42 9a15.91 15.91 0 0 1 4.7-2.88" /><path d="M8.53 16.11a6 6 0 0 1 6.95 0" /><line x1="12" y1="20" x2="12.01" y2="20" />
    </svg>
  ),
  copy: (
    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <rect x="9" y="9" width="13" height="13" rx="2" ry="2" /><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
    </svg>
  ),
  check: (
    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
      <polyline points="20 6 9 17 4 12" />
    </svg>
  ),
  menu: (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <line x1="3" y1="12" x2="21" y2="12" /><line x1="3" y1="6" x2="21" y2="6" /><line x1="3" y1="18" x2="21" y2="18" />
    </svg>
  ),
  x: (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <line x1="18" y1="6" x2="6" y2="18" /><line x1="6" y1="6" x2="18" y2="18" />
    </svg>
  ),
  externalLink: (
    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" /><polyline points="15 3 21 3 21 9" /><line x1="10" y1="14" x2="21" y2="3" />
    </svg>
  ),
  info: (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" /><line x1="12" y1="16" x2="12" y2="12" /><line x1="12" y1="8" x2="12.01" y2="8" />
    </svg>
  ),
};

/* ────────────────────────────────────────────────────────────
 *  Lightweight Syntax Highlighter — single-pass tokenizer
 *  Uses one combined regex per language so tokens never
 *  conflict with HTML generated by earlier matches.
 * ──────────────────────────────────────────────────────────── */
function escapeHtml(text: string): string {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function highlightCode(code: string, lang: string): string {
  if (['tsx', 'ts', 'typescript', 'javascript', 'js', 'jsx'].includes(lang)) {
    // Single combined regex — order matters (first match wins):
    // 1. Single-line comments  2. Template literals  3. Strings  4. Keywords  5. Numbers
    const tokenRegex = /(\/\/.*$)|(`[^`]*`)|(["'])(?:(?!\3)[^\\]|\\.)*\3|\b(import|export|from|const|let|var|function|return|if|else|new|class|extends|default|type|interface|async|await|try|catch|throw|typeof|instanceof|void|null|undefined|true|false)\b|(\b\d+\.?\d*\b)/gm;

    let result = '';
    let lastIndex = 0;

    for (const match of code.matchAll(tokenRegex)) {
      // Append escaped text before this token
      result += escapeHtml(code.slice(lastIndex, match.index));
      const token = match[0];

      if (match[1]) {
        result += `<span class="hl-cmt">${escapeHtml(token)}</span>`;
      } else if (match[2]) {
        result += `<span class="hl-str">${escapeHtml(token)}</span>`;
      } else if (match[3]) {
        result += `<span class="hl-str">${escapeHtml(token)}</span>`;
      } else if (match[4]) {
        result += `<span class="hl-kw">${escapeHtml(token)}</span>`;
      } else if (match[5]) {
        result += `<span class="hl-num">${escapeHtml(token)}</span>`;
      }

      lastIndex = match.index! + token.length;
    }

    result += escapeHtml(code.slice(lastIndex));
    return result;

  } else if (lang === 'bash' || lang === 'sh') {
    const tokenRegex = /(#.*$)|(["'])(?:(?!\2)[^\\]|\\.)*\2|(--\w[\w-]*)|\b(npm|npx|cd|git|clone|install|run|dev|build|publish|login)\b/gm;

    let result = '';
    let lastIndex = 0;

    for (const match of code.matchAll(tokenRegex)) {
      result += escapeHtml(code.slice(lastIndex, match.index));
      const token = match[0];

      if (match[1]) {
        result += `<span class="hl-cmt">${escapeHtml(token)}</span>`;
      } else if (match[2]) {
        result += `<span class="hl-str">${escapeHtml(token)}</span>`;
      } else if (match[3]) {
        result += `<span class="hl-flag">${escapeHtml(token)}</span>`;
      } else if (match[4]) {
        result += `<span class="hl-kw">${escapeHtml(token)}</span>`;
      }

      lastIndex = match.index! + token.length;
    }

    result += escapeHtml(code.slice(lastIndex));
    return result;
  }

  return escapeHtml(code);
}

/* ────────────────────────────────────────────────────────────
 *  CodeBlock Component
 * ──────────────────────────────────────────────────────────── */
function CodeBlock({ code, lang = 'tsx' }: { code: string; lang?: string }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="docs-codeblock">
      <div className="docs-codeblock-header">
        <span className="docs-codeblock-lang">{lang}</span>
        <button className="docs-copy-btn" onClick={handleCopy}>
          {copied ? <>{Icons.check} Copied</> : <>{Icons.copy} Copy</>}
        </button>
      </div>
      <pre><code dangerouslySetInnerHTML={{ __html: highlightCode(code.trim(), lang) }} /></pre>
    </div>
  );
}

/* ────────────────────────────────────────────────────────────
 *  Section data
 * ──────────────────────────────────────────────────────────── */
const sections = [
  { id: 'getting-started', title: 'Getting Started' },
  { id: 'installation', title: 'Installation' },
  { id: 'quick-start', title: 'Quick Start' },
  { id: 'react-hook', title: 'React Hook API' },
  { id: 'core-api', title: 'Core API' },
  { id: 'presence', title: 'Presence & Cursors' },
  { id: 'events', title: 'Events' },
  { id: 'server-setup', title: 'Server Setup' },
  { id: 'examples', title: 'Examples' },
];

/* ────────────────────────────────────────────────────────────
 *  DocsPage Component
 * ──────────────────────────────────────────────────────────── */
export default function DocsPage() {
  const [activeSection, setActiveSection] = useState('getting-started');
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);

  // Scroll to top when the docs page mounts
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  // Intersection Observer to highlight active sidebar link on scroll
  useEffect(() => {
    const observers: IntersectionObserver[] = [];

    // Small delay to ensure DOM is fully rendered
    const timer = setTimeout(() => {
      sections.forEach(({ id }) => {
        const el = document.getElementById(`doc-${id}`);
        if (!el) return;
        const obs = new IntersectionObserver(
          ([entry]) => {
            if (entry.isIntersecting) setActiveSection(id);
          },
          { rootMargin: '-80px 0px -50% 0px', threshold: 0 }
        );
        obs.observe(el);
        observers.push(obs);
      });
    }, 100);

    return () => {
      clearTimeout(timer);
      observers.forEach(o => o.disconnect());
    };
  }, []);

  const scrollTo = useCallback((id: string) => {
    const el = document.getElementById(`doc-${id}`);
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', block: 'start' });
      setActiveSection(id);
      setSidebarOpen(false);
    }
  }, []);

  return (
    <div className="docs-page">
      {/* Mobile toggle */}
      <button className="docs-sidebar-toggle" onClick={() => setSidebarOpen(!sidebarOpen)}>
        {sidebarOpen ? Icons.x : Icons.menu}
        <span style={{ marginLeft: 8 }}>Docs Menu</span>
      </button>

      {/* Sidebar */}
      <aside className={`docs-sidebar ${sidebarOpen ? 'open' : ''}`}>
        <div className="docs-sidebar-header">
          <span className="docs-sidebar-icon">{Icons.book}</span>
          <span>Documentation</span>
        </div>
        <nav className="docs-sidebar-nav">
          {sections.map(({ id, title }) => (
            <button
              key={id}
              className={`docs-nav-link ${activeSection === id ? 'active' : ''}`}
              onClick={() => scrollTo(id)}
            >
              {title}
            </button>
          ))}
        </nav>
        <div className="docs-sidebar-badge">
          <span className="docs-version-badge">v1.0.0</span>
          <a href="https://www.npmjs.com/package/collabdoc-sdk" target="_blank" rel="noopener" className="docs-npm-link">
            npm {Icons.externalLink}
          </a>
        </div>
      </aside>

      {/* Content */}
      <div className="docs-content" ref={contentRef}>

        {/* ─── Getting Started ───────────────────────── */}
        <section id="doc-getting-started" className="docs-section">
          <h2>Getting Started</h2>
          <p>
            <strong>collabdoc-sdk</strong> is a real-time collaborative document editing SDK powered by
            <strong> Yjs CRDTs</strong> and <strong>Socket.IO</strong>. It lets you add Google Docs-style
            collaboration to any React application in minutes.
          </p>
          <div className="docs-feature-grid">
            <div className="docs-feature-card">
              <span className="docs-feature-icon">{Icons.refresh}</span>
              <h4>Conflict-Free</h4>
              <p>Yjs CRDTs guarantee zero data loss, even with simultaneous edits from multiple users.</p>
            </div>
            <div className="docs-feature-card">
              <span className="docs-feature-icon">{Icons.zap}</span>
              <h4>Real-Time</h4>
              <p>Sub-50ms latency via Socket.IO WebSockets. Changes appear instantly for all users.</p>
            </div>
            <div className="docs-feature-card">
              <span className="docs-feature-icon">{Icons.users}</span>
              <h4>Presence</h4>
              <p>See who's online and where their cursor is. Build awareness into your UI effortlessly.</p>
            </div>
            <div className="docs-feature-card">
              <span className="docs-feature-icon">{Icons.wifiOff}</span>
              <h4>Offline Support</h4>
              <p>Keep editing while disconnected. Changes merge seamlessly on reconnect.</p>
            </div>
          </div>
        </section>

        {/* ─── Installation ──────────────────────────── */}
        <section id="doc-installation" className="docs-section">
          <h2>Installation</h2>
          <p>Install the SDK from npm:</p>
          <CodeBlock lang="bash" code={`npm install collabdoc-sdk`} />
          <p>That's it! The SDK bundles all its dependencies (<code>yjs</code>, <code>socket.io-client</code>) internally, so you don't need to install anything else.</p>
          <div className="docs-callout">
            {Icons.info}
            <span><strong>Note:</strong> The SDK requires <code>react</code> &gt;= 18 as a peer dependency (you already have it in your project).</span>
          </div>
        </section>

        {/* ─── Quick Start ───────────────────────────── */}
        <section id="doc-quick-start" className="docs-section">
          <h2>Quick Start</h2>
          <p>Add real-time collaboration to a React component in just a few lines:</p>
          <CodeBlock lang="tsx" code={`import { useCollabDoc } from 'collabdoc-sdk/react';

function CollaborativeEditor() {
  const { doc, isConnected, isSynced, presence } = useCollabDoc({
    roomId: 'my-document-123',
    serverUrl: 'https://your-collab-server.com',
    user: { name: 'Alice', color: '#0070f3' },
    token: 'your-jwt-token', // optional
  });

  // Get the collaborative text
  const yText = doc?.getText('content');
  const text = yText?.toString() || '';

  return (
    <div>
      <p>{isConnected ? 'Connected' : 'Connecting...'}</p>
      <p>{presence.size} users online</p>
      <textarea value={text} onChange={handleChange} />
    </div>
  );
}`} />
          <p>The <code>useCollabDoc</code> hook handles all WebSocket connections, CRDT synchronization, and presence tracking automatically.</p>
        </section>

        {/* ─── React Hook API ────────────────────────── */}
        <section id="doc-react-hook" className="docs-section">
          <h2>React Hook API</h2>
          <h3><code>useCollabDoc(options)</code></h3>
          <p>The primary way to use the SDK in React applications.</p>

          <h4>Options</h4>
          <div className="docs-table-wrapper">
            <table className="docs-table">
              <thead>
                <tr><th>Option</th><th>Type</th><th>Required</th><th>Description</th></tr>
              </thead>
              <tbody>
                <tr><td><code>roomId</code></td><td><code>string</code></td><td>Yes</td><td>Unique document/room identifier</td></tr>
                <tr><td><code>serverUrl</code></td><td><code>string</code></td><td>Yes</td><td>CollabDoc WebSocket server URL</td></tr>
                <tr><td><code>user</code></td><td><code>{'{ name, color }'}</code></td><td>No</td><td>User info for presence</td></tr>
                <tr><td><code>token</code></td><td><code>string</code></td><td>No</td><td>JWT token for authentication</td></tr>
              </tbody>
            </table>
          </div>

          <h4>Return Values</h4>
          <div className="docs-table-wrapper">
            <table className="docs-table">
              <thead>
                <tr><th>Field</th><th>Type</th><th>Description</th></tr>
              </thead>
              <tbody>
                <tr><td><code>doc</code></td><td><code>CollabDoc | null</code></td><td>The CollabDoc instance for direct manipulation</td></tr>
                <tr><td><code>docState</code></td><td><code>Record&lt;string, any&gt;</code></td><td>Document state as plain JSON (auto-updated)</td></tr>
                <tr><td><code>isConnected</code></td><td><code>boolean</code></td><td>WebSocket connection status</td></tr>
                <tr><td><code>isSynced</code></td><td><code>boolean</code></td><td>Initial sync complete</td></tr>
                <tr><td><code>presence</code></td><td><code>Map&lt;number, AwarenessUser&gt;</code></td><td>Online users and their cursor positions</td></tr>
                <tr><td><code>error</code></td><td><code>Error | null</code></td><td>Connection/auth errors</td></tr>
              </tbody>
            </table>
          </div>

          <CodeBlock lang="tsx" code={`const {
  doc,        // CollabDoc instance
  docState,   // { key: value, ... }
  isConnected,
  isSynced,
  presence,   // Map<clientId, { user, cursor }>
  error,
} = useCollabDoc({ roomId, serverUrl, user, token });`} />
        </section>

        {/* ─── Core API ──────────────────────────────── */}
        <section id="doc-core-api" className="docs-section">
          <h2>Core API</h2>
          <p>You can also use the SDK without React by importing the <code>CollabDoc</code> class directly.</p>

          <CodeBlock lang="ts" code={`import { CollabDoc } from 'collabdoc-sdk';

const doc = new CollabDoc({
  roomId: 'my-document',
  serverUrl: 'https://your-server.com',
  user: { name: 'Bob', color: '#34d399' },
});

doc.connect();`} />

          <h3>Key-Value API</h3>
          <p>Store and retrieve structured data using nested paths:</p>
          <CodeBlock lang="ts" code={`// Set a value at a nested path
doc.set(['settings', 'theme'], 'dark');
doc.set(['users', 0, 'name'], 'Alice');

// Read a value
doc.get(['settings', 'theme']); // 'dark'

// Delete a key
doc.delete(['settings', 'theme']);

// Get the entire document as a plain JSON object
const state = doc.getDocumentState();
// { settings: { ... }, users: [...] }`} />

          <h3>Rich Text API</h3>
          <p>For collaborative text editing, use the <code>getText()</code> method which returns a Yjs <code>Y.Text</code> instance:</p>
          <CodeBlock lang="ts" code={`const yText = doc.getText('content');

// Insert text at position
yText.insert(0, 'Hello, World!');

// Delete text (position, length)
yText.delete(0, 5);

// Read the full text
console.log(yText.toString()); // 'Hello, World!'

// Observe changes
yText.observe((event) => {
  console.log('Text changed:', yText.toString());
});`} />

          <h3>Y.Doc Access</h3>
          <p>For advanced use cases, access the underlying Yjs document:</p>
          <CodeBlock lang="ts" code={`const ydoc = doc.getYDoc();

// Use any Yjs shared type
const yMap = ydoc.getMap('myMap');
const yArray = ydoc.getArray('myArray');

// Batch multiple operations in one transaction
ydoc.transact(() => {
  yMap.set('key1', 'value1');
  yMap.set('key2', 'value2');
});`} />
        </section>

        {/* ─── Presence & Cursors ────────────────────── */}
        <section id="doc-presence" className="docs-section">
          <h2>Presence & Cursors</h2>
          <p>The SDK includes built-in presence awareness to show who is online and where they are editing.</p>

          <h3>Setting Cursor Position</h3>
          <CodeBlock lang="ts" code={`// Broadcast your cursor position
doc.setCursor({ path: 'content', offset: 42 });

// Clear cursor (e.g., on blur)
doc.setCursor(null);`} />

          <h3>Reading Presence</h3>
          <CodeBlock lang="tsx" code={`// In React — presence is auto-updated via useCollabDoc
const { presence } = useCollabDoc({ ... });

// Render online users
const users = Array.from(presence.entries());
users.map(([clientId, state]) => (
  <div key={clientId} style={{ color: state.user?.color }}>
    {state.user?.name}
    {state.cursor && \` (at offset \${state.cursor.offset})\`}
  </div>
));`} />

          <h3>Without React</h3>
          <CodeBlock lang="ts" code={`// Listen for presence updates
doc.on('awareness', (states) => {
  for (const [clientId, state] of states) {
    console.log(state.user?.name, 'cursor at', state.cursor?.offset);
  }
});

// Get current presence snapshot
const allUsers = doc.getPresence();`} />
        </section>

        {/* ─── Events ────────────────────────────────── */}
        <section id="doc-events" className="docs-section">
          <h2>Events</h2>
          <p>The <code>CollabDoc</code> class emits events for connection, sync, and document changes:</p>

          <div className="docs-table-wrapper">
            <table className="docs-table">
              <thead>
                <tr><th>Event</th><th>Payload</th><th>Description</th></tr>
              </thead>
              <tbody>
                <tr><td><code>connect</code></td><td>—</td><td>WebSocket connected to server</td></tr>
                <tr><td><code>disconnect</code></td><td><code>reason: string</code></td><td>WebSocket disconnected</td></tr>
                <tr><td><code>synced</code></td><td>—</td><td>Initial document sync complete</td></tr>
                <tr><td><code>change</code></td><td><code>{'{ origin }'}</code></td><td>Document state changed (<code>local</code> or <code>remote</code>)</td></tr>
                <tr><td><code>awareness</code></td><td><code>Map&lt;id, state&gt;</code></td><td>Presence data updated</td></tr>
                <tr><td><code>error</code></td><td><code>Error</code></td><td>Connection or auth error</td></tr>
              </tbody>
            </table>
          </div>

          <CodeBlock lang="ts" code={`doc.on('connect', () => console.log('Connected!'));
doc.on('synced', () => console.log('Document synced!'));
doc.on('change', ({ origin }) => {
  console.log(\`Change from \${origin}\`);
  console.log('Current state:', doc.getDocumentState());
});
doc.on('error', (err) => console.error('Error:', err));`} />
        </section>

        {/* ─── Server Setup ──────────────────────────── */}
        <section id="doc-server-setup" className="docs-section">
          <h2>Server Setup</h2>
          <p>The SDK requires a CollabDoc-compatible WebSocket server. You can self-host it or use the demo server.</p>

          <h3>Quick Start (Self-Hosted)</h3>
          <CodeBlock lang="bash" code={`# Clone the repository
git clone https://github.com/gautamkumar34/Real-time-collaboration-SDK.git
cd Real-time-collaboration-SDK/server

# Install dependencies
npm install

# Set environment variables
cp .env.example .env
# Edit .env with your database URL and JWT secret

# Start the server
npm run dev`} />

          <h3>Environment Variables</h3>
          <div className="docs-table-wrapper">
            <table className="docs-table">
              <thead>
                <tr><th>Variable</th><th>Required</th><th>Description</th></tr>
              </thead>
              <tbody>
                <tr><td><code>PORT</code></td><td>No</td><td>Server port (default: 8080)</td></tr>
                <tr><td><code>DATABASE_URL</code></td><td>No</td><td>PostgreSQL connection string (for persistence)</td></tr>
                <tr><td><code>SUPABASE_SECRET_KEY</code></td><td>No</td><td>JWT secret for token verification</td></tr>
                <tr><td><code>CORS_ORIGIN</code></td><td>No</td><td>Allowed origins (comma-separated or <code>*</code>)</td></tr>
                <tr><td><code>STORE_BACKEND</code></td><td>No</td><td><code>memory</code> or <code>postgres</code> (default: memory)</td></tr>
              </tbody>
            </table>
          </div>

          <h3>Deploy to Render</h3>
          <p>The server can be deployed to <a href="https://render.com" target="_blank" rel="noopener">Render</a> as a Web Service. Connect your GitHub repo, set the build command to <code>npm install && npm run build</code>, and the start command to <code>npm start</code>.</p>
        </section>

        {/* ─── Examples ──────────────────────────────── */}
        <section id="doc-examples" className="docs-section">
          <h2>Examples</h2>

          <h3>Collaborative Text Editor</h3>
          <p>A complete example showing real-time text editing with cursor sync and online presence:</p>
          <CodeBlock lang="tsx" code={`import { useState, useEffect, useRef } from 'react';
import { useCollabDoc } from 'collabdoc-sdk/react';

export default function Editor({ documentId }) {
  const [text, setText] = useState('');
  const prevTextRef = useRef('');

  const { doc, isConnected, presence } = useCollabDoc({
    roomId: documentId,
    serverUrl: 'https://your-server.com',
    user: { name: 'Alice', color: '#0070f3' },
  });

  // Sync Yjs text to React state
  useEffect(() => {
    if (!doc) return;
    const yText = doc.getText('content');

    const observer = () => {
      const t = yText.toString();
      setText(t);
      prevTextRef.current = t;
    };

    setText(yText.toString());
    yText.observe(observer);
    return () => yText.unobserve(observer);
  }, [doc]);

  // Handle user typing with diff-based updates
  const handleChange = (e) => {
    if (!doc) return;
    const yText = doc.getText('content');
    const newVal = e.target.value;
    const oldVal = prevTextRef.current;

    let i = 0;
    while (i < oldVal.length && i < newVal.length && oldVal[i] === newVal[i]) i++;

    let j = 0;
    while (
      j < oldVal.length - i &&
      j < newVal.length - i &&
      oldVal[oldVal.length - 1 - j] === newVal[newVal.length - 1 - j]
    ) j++;

    const deleteCount = oldVal.length - i - j;
    const insertText = newVal.substring(i, newVal.length - j);

    doc.getYDoc().transact(() => {
      if (deleteCount > 0) yText.delete(i, deleteCount);
      if (insertText) yText.insert(i, insertText);
    });

    setText(newVal);
    prevTextRef.current = newVal;
    doc.setCursor({ path: 'content', offset: e.target.selectionStart });
  };

  return (
    <div>
      <div>{isConnected ? 'Connected' : 'Offline'} — {presence.size} online</div>
      <textarea value={text} onChange={handleChange} rows={20} />
    </div>
  );
}`} />

          <h3>Key-Value Store</h3>
          <p>Use the SDK as a real-time synchronized key-value store:</p>
          <CodeBlock lang="ts" code={`import { CollabDoc } from 'collabdoc-sdk';

const doc = new CollabDoc({
  roomId: 'shared-config',
  serverUrl: 'wss://your-server.com',
});

doc.on('synced', () => {
  // Set values
  doc.set(['config', 'theme'], 'dark');
  doc.set(['config', 'fontSize'], 16);
  doc.set(['users'], [{ name: 'Alice' }, { name: 'Bob' }]);

  // Read values
  console.log(doc.get(['config', 'theme'])); // 'dark'
  console.log(doc.getDocumentState());
  // { config: { theme: 'dark', fontSize: 16 }, users: [...] }
});

doc.on('change', ({ origin }) => {
  if (origin === 'remote') {
    console.log('Remote update:', doc.getDocumentState());
  }
});

doc.connect();`} />
        </section>

      </div>
    </div>
  );
}
